default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: kadai_development
  
test:
  <<: *default
  database: kadai_test

production:
  <<: *default
  database: kadai_production
  username: kadai
  password: <%= ENV['KADAI_DATABASE_PASSWORD'] %>
